### ISSUE TITLE
Exception while using /chat

### ISSUE THREAD

**Issue by revblueldd** [armintum/Bard-Discord-bot#10]
I did a git pull / and ran pip3 install for the updated requirements.txt, and am getting an exception when I try to use the chat command:

[2023-06-04 18:38:18] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Bard-Discord-bot\main.py", line 176, in chat
    response = await generate_response(message)
  File "C:\Bard-Discord-bot\main.py", line 38, in generate_response
    response = bard.ask(prompt)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Bard.py", line 83, in ask
    return self.loop.run_until_complete(self.async_chatbot.ask(message))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 625, in run_until_complete
    self._check_running()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 586, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: RuntimeError: Cannot run the event loop while another loop is running
C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py:1252: RuntimeWarning: coroutine 'AsyncChatbot.ask' was never awaited
  await self.on_error(interaction, e)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by plon** [comment]
This error is due to version 1.3.0 of the google bard reversed API having async. I updated the dependencies and downgraded it to 1.2.2

**Comment by armintum** [comment]
Seems like google has changed the schema of the response so newest google bard reversed API version is necessary. working on fix

**Comment by plon** [comment]
It is an issue with the bard reversed API

**Comment by revblueldd** [comment]
Understood and thanks as always!

**Comment by revblueldd** [comment]
This is working now, thank you!
