### ISSUE TITLE
Exception stating "cannot send an empty message" when using /chat

### ISSUE THREAD

**Issue by revblueldd** [armintum/Bard-Discord-bot#7]
A User was chatting with the bot and it generated an exception.   See screenshot and exception:

![Screenshot 2023-05-18 171926](https://github.com/Qoct/Bard-Discord-bot/assets/133729554/c8391501-e56b-49eb-9a3f-b8e377877d61)

[2023-05-18 16:33:45] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Bard-Discord-bot\main.py", line 140, in chat
    await interaction.channel.send(chunk)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

**Comment by revblueldd** [comment]
I suspect it might be related to the formatting used on text in the chat prompt - notice the "queen - obscene" part.

I was able to get it to fail with "/chat what about *this*?"

**Comment by revblueldd** [comment]
Interestingly an asterisk works as a math operator like with "/chat what is 4 * 2?" but does not when you use a pair of them to format the text between them.

**Comment by plon** [comment]
Can you paste the text that you are inputting here?

**Comment by revblueldd** [comment]
I did in my example "/chat what about *this*?" but this interface is also applying the style so you can't see it.   The word "this" is surrounded by asterisks in my example.

**Comment by plon** [comment]
That's odd. It works for me. 
<img width="421" alt="Screenshot 2023-05-18 at 8 56 35 PM" src="https://github.com/Qoct/Bard-Discord-bot/assets/115377622/b7c73f0f-4166-4e88-9e52-2bc9e99987e6">

**Comment by revblueldd** [comment]
After the latest git pull it is now working for me as well.

**Comment by revblueldd** [comment]
I just got this exception again.  I have no clue what might be causing it.   

![Screenshot 2023-05-18 214945](https://github.com/Qoct/Bard-Discord-bot/assets/133729554/758ac8d0-2ed7-4bb3-9729-a37fec051248)

[2023-05-18 21:47:03] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Bard-Discord-bot\main.py", line 148, in chat
    await interaction.channel.send(chunk)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

**Comment by revblueldd** [comment]
The user above reposted the same /chat as in the screenshot afterwards, and it worked that time.   I cannot pin down any reason why it is intermittent like that.  

The only people who were trying this at this time were myself and one other (and not simultaneously), so I do not think that concurrency is the issue.

Right after it worked again, it then failed twice and worked the 3rd time after a reset.  The reset may have helped but am not confident of that.   This may well be an issue with the projects this is based on and nothing you can do about that part, other than perhaps some error handling to display a graceful message when the call fails.

![Screenshot 2023-05-18 215921](https://github.com/Qoct/Bard-Discord-bot/assets/133729554/7d99ae31-baea-4eba-9009-ae1808880874)

**Comment by plon** [comment]
This is most likely an issue with the reversed Bard API that the bot uses.

**Comment by revblueldd** [comment]
I agree - perhaps could put a generic error similar to the other one, when the call fails?

**Comment by plon** [comment]
Done.
